name: "diamond blastp"
description: DIAMOND is a sequence aligner for protein and translated DNA searches, designed for high performance analysis of big sequence data.
authors:
  - Nikos Tsardakas Renhuldt
  - Kim Philipp Jablonski
